### PR TITLE
More effient graph-edge storage, some docs

### PR DESCRIPTION
**Pull request by orottier**
Hey @b-ma , for your information. Docs are still a work in progress!

### CODE REVIEW

**Comment by b-ma** [comment]
Hey, looks pretty good and comments are really helpful to understand better the graph logic. I ran through the whole `graph.rs` file this time and I have 1 related question / remarks, why is this necessary to loop through all the nodes: 

```rs
// visit all registered nodes, depth first search 
self.nodes.keys().for_each(|&i| {
  self.visit(
    i,
    &mut marked,
    &mut marked_temp,
    &mut ordered,
    &mut in_cycle,
  );
});
```

At first sight, I wonder why this is necessary to loop through all `self.nodes` because as the graph is guaranteed to have one single output (.e.g. `listener`) and `visit` is recursive, something like (without the loop) should do the trick no?

```rs
// visit all registered nodes, depth first search 
self.visit(
  ListenerIndex,
  &mut marked,
  &mut marked_temp,
  &mut ordered,
  &mut in_cycle,
);
```
I would imagine that this could gives you all the nodes that are currently connected, and would more be deterministic as it wouldn't rely anymore on `keys` and as the connections are sorted in `SmallVec`s?

**Comment by orottier** [comment]
> Why is this necessary to loop through all the nodes there?

Great question. I think the main thing to realize is that there may be pieces of the audio graph that are not connected to the destination node.

For example, you may want to use the web-audio-api to create a visual spectogram of a sound input. In this case, you don't want to play the audio on the speakers, but you want to use an `AnalyzerNode` and write the frequency values to a html `canvas`. This means we will never reach the audio input node if we would start from the destination node and visit the connected nodes from there.

My implementation is much inspired by https://webaudio.github.io/web-audio-api/#rendering-loop . Definitely worth reading.

Sidenote, the recursive implementation is a bit strange in rust because of all the mutable borrows I need to carry around. I may rewrite it into a sequential (non recursive) variant. Let me check if that makes it more readable.

**Comment by b-ma** [comment]
Ok good point, really didn't think of these cases (that would make a nice comment in the code :). For the recursive implementation I think it's quite readable actually, there are some `Rust` weirdness for sure... but it's also kind of pedagogical for newbies such as me.

**Comment by orottier** [comment]
> note: Maybe it would be interesting to try to see with the spec people if defining a kind of Output or Sink type (which can be only a few nodes I guess), just as there are well defined Sources wouldn't worth the effort?

Interesting thought, but I think this will be hard in practise. For example, you could set up a microphone input and connect it to a large delay node. Then after a minute or so, you could connect the delay node to the output node. In this case, the mic and delay should really render every frame, even though they are not (yet) connected to the output. Basically any non-pure Node (means: having side effects such as caching, moving data to user side, etc) should be considered a Sink in this case, which could be quite many of them. This would decrease the usefulness in my opinion

**Pull request merged**
