### PR TITLE
Assess performance impact of MAX_CHANNEL_COUNT (32 -> 256)

### PR DESCRIPTION
**Pull request by orottier**
Some investigations for https://github.com/ircam-ismm/node-web-audio-api/issues/23#issuecomment-1637078022

### CODE REVIEW

**Comment by b-ma** [comment]
Whow quite impressive

**Comment by orottier** [comment]
Indeed. But we should realize these CI benchmark are rather synthetic because they are microbenchmarks, not real world workloads. But the benchmarks.rs example shows a similar - less extreme - trend.

For fun and giggles I will perform another run with 4 channels max, but this is not permissable.
E.g. even if the audio output hardware is stereo, it is possible to have intermediate buffers in the audio graph with 32 channels (when using a large ChannelMergerNode maybe) which are downmixed before they reach the destination node.

All in all this shows we should not increase the MAX_CHANNEL_COUNT to a large number because this will negatively affect many users. I will continue to explore solutions

**Comment by orottier** [comment]
@b-ma with the issues around 32+ channels counts resolved, I think it's better to leave this as it is and focus on other things. Unless you think there's merit to supporting larger channels counts

**Comment by b-ma** [comment]
Yup this is really ok I think. That's really niche requirements and it's always possible to make a specific build changing the MAX_CHANNEL_COUNT constant if really required

**Pull request closed without merging**
