### PR TITLE
Use default sample rate for output device, instead of requesting highest

### LINKED ISSUE #28: Sample rate high on ALSA
context.sample_rate() displays a sample rate of 384 000 Hz on my ALSA system.
This default sample rate is coming from the CPAL default output config.

Possible solution: try to build a stream with a lower sample rate before defaulting into the CPAL default sample rate.

### PR DESCRIPTION
**Pull request by orottier**
This is probably best for stability. Users can use the
AudioContextOptions if they require specific sample rates

I'm reasonably sure this fixes #28 but I don't run ALSA so I cannot verify

### CODE REVIEW

**Comment by b-ma** [comment]
I can set up a Raspberry Pi to check that, I let you know

**Comment by b-ma** [comment]
Finally found some little time to test on a RPi 4 (4GB of RAM) w/ a HIFIBERRY DAC+ ADC (which can go up to 192kHz, cf. https://www.hifiberry.com/shop/boards/hifiberry-dac-adc/)

And result shows:

```
AudioContextLatencyCategory::Interactive
- SampleRate: 44100
- BaseLatency: 0.0
-------------------------------------------------
+ currentTime 0.0
+ OutputLatency: 0.0
-------------------------------------------------
+ currentTime 1.0042630385487528
+ OutputLatency: 0.00217687
-------------------------------------------------
+ currentTime 2.00562358276644
+ OutputLatency: 0.00154195
-------------------------------------------------
```

So this looks good ! (no problem for building and so on :)

For the record here are the benches

```
+ id      | name                                                                     | duration (ms) | Speedup vs. realtime  | buffer.duration (s)
- 1       | Baseline (silence)                                                       | 191           | 628.3x                | 120
- 2       | Simple source test without resampling (Mono)                             | 630           | 190.5x                | 120
- 3       | Simple source test without resampling (Stereo)                           | 794           | 151.1x                | 120
- 4       | Simple source test without resampling (Stereo and positionnal)           | 2030          | 59.1x                 | 120
- 5       | Simple source test with resampling (Mono)                                | 627           | 191.4x                | 120
- 6       | Simple source test with resampling (Stereo)                              | 779           | 154.0x                | 120
- 7       | Simple source test with resampling (Stereo and positionnal)              | 2021          | 59.4x                 | 120
- 8       | Upmix without resampling (Mono -> Stereo)                                | 691           | 173.7x                | 120
- 9       | Downmix without resampling (Stereo -> Mono)                              | 737           | 162.8x                | 120
- 10      | Simple mixing (100x same buffer) - be careful w/ volume here!            | 13192         | 2.3x                  | 30
- 11      | Simple mixing (100 different buffers) - be careful w/ volume here!       | 14138         | 2.1x                  | 30
- 12      | Simple mixing with gains                                                 | 2957          | 40.6x                 | 120
- 13      | Granular synthesis                                                       | 103676        | 0.1x                  | 7.5
- 14      | Synth (Sawtooth with Envelope)                                           | 41535         | 2.9x                  | 120
- 15      | Synth (Sawtooth with gain - no automation)                               | 36832         | 3.3x                  | 120
- 16      | Synth (Sawtooth without gain)                                            | 15603         | 7.7x                  | 120
- 17      | Substractive Synth                                                       | 4854          | 24.7x                 | 120
- 18      | Stereo panning                                                           | 2005          | 59.9x                 | 120
- 19      | Stereo panning with automation                                           | 1999          | 60.0x                 | 120
- 20      | Sawtooth with automation                                                 | 515           | 233.0x                | 120
```

I will try some other examples later (need to find a speaker...)

**Comment by orottier** [comment]
Great! Thanks for testing

**Comment by uklotzde** [comment]
No indication that the result is awful noise:

```
$ RUST_LOG=debug cargo run --release --example mono
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/examples/mono`
[2023-06-18T09:06:25Z INFO  web_audio_api::io::cpal] Audio Output Host: cpal Alsa
[2023-06-18T09:06:25Z INFO  web_audio_api::io::cpal] Output device: Ok("default")
[2023-06-18T09:06:25Z DEBUG web_audio_api::io::cpal] Attempt output stream with prefered config: StreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Fixed(128) }
[2023-06-18T09:06:25Z DEBUG web_audio_api::io::cpal] Output stream set up successfully
stereo
mono
stereo
```

**Pull request merged**
