### PR TITLE
Flush denormal float values in audio graph processing

### LINKED ISSUE #194: How to deal with subnormal floats?
> FYI this branch breaks SIMD-optimizations.

Damned !

> I'm wondering if this check (and the one we just added to the AudioParam) is worth it. We are slowing down all architectures to save some performance on exotic ones?

I'm afraid they are not really exotic platforms... Intel x86_64 just like mine... ARMv8 feels more exotic to me :)

I will remove that from the GainNode for now, maybe it's best to open an issue to make sure we don't forget the possible problem and wait until we both better understand it and (hopefully) have a better solution to propose

I wouldn't compare this with the check in the AudioParam that just happen once in a while in very specific conditions though

https://stackoverflow.com/questions/9314534/why-does-changing-0-1f-to-0-slow-down-performance-by-10x/9314926#9314926, there is also a comment about audio application there

_Originally posted by @b-ma in https://github.com/orottier/web-audio-api-rs/pull/191#discussion_r937352505_

### PR DESCRIPTION
**Pull request by orottier**
Fixes #194

### CODE REVIEW

**Comment by orottier** [comment]
Okay, with the final version I think the performance regression is acceptable

**Comment by b-ma** [comment]
Cool looks nice ! 
I think there are still some places in the code (i.e. `AudioParam`) where we check this manually, I will try to have a look soon

(for info, I will be completely off next week)

**Pull request merged**
