### PR TITLE
AudioProcessor::process now returns boolean for tail_time

### PR DESCRIPTION
**Pull request by orottier**
Fixing issue #58 - conform to spec

### CODE REVIEW

**Comment by b-ma** [comment]
Hey, looks good to me as far as I can say. Just one related remark (which could maybe go into #34) about that all `AudioScheduledSourceNode`s should probably have the same strategy that the one implemented in the `OscillatorNode`

**Comment by orottier** [comment]
Thanks for having a look @b-ma 

What do you mean exactly? As I understand, the 
`impl<R: MediaStream> AudioProcessor for MediaStreamRenderer<R>`
is slightly more complex than the `OscillatorRenderer` as it can also quit due to errors or an exhausted media stream.
After your comment I did clean up the code a bit

**Comment by b-ma** [comment]
Hey, I was thinking more specifically about `AudioBufferSourceNode`, `ConstantSourceNode` and `OscillatorNode` (which derive from the `AudioScheduledSourceNode`), not about the stream sources which as you say have to deal with more complex issues. 

Probably this is another discussion, and I might clearly be wrong as I didn't dig enough into the implementation, but at first sight reasoning about `AudioBufferSourceNode` as a stream reader seems quite strange to me (as it reads PCM data from an `AudioBuffer` that is fully loaded in memory), while it would be correct for `MediaElementAudioSourceNode` or `MediaStreamAudioSourceNode`. But, this is maybe also just a terminology problem.

Anyway, even if relevant, this discussion is certainly way beyond your current changes which make the code far more simple to understand!

**Comment by orottier** [comment]
I see your point and will amend the ticket about smarter tail time implementations.
For audiobuffer sources, the input needs to be cut in pieces of BUFFER_SIZE samples. It could definitely be optimised

**Pull request merged**
