### PR TITLE
Change SampleRate type from u32 to f32 (issue #50)

### PR DESCRIPTION
**Pull request by orottier**
To be fair, u32 is the better choice as it disallows negative values, and has better numerical precision 🤷‍♂️

### CODE REVIEW

**Comment by b-ma** [comment]
I'm a bit off these days, but I will have a look soon

**Comment by orottier** [comment]
No hurries, enjoy the holidays.

I'm actually reconsidering this PR. To continue using u32 internally but expose sample rate as f32 to the user. This would be conform the spec and still have the benefit of u32. All serious rust audio libs seem to use u32 for sample rates..

**Comment by b-ma** [comment]
Hey, nothing much to say there... I also find the `float` sample rate rather strange (never seen a sample rate with a decimal part), tried to look into the spec issues to see if this has been discussed somewhere and understand the rational but couldn't anything neither...

**Comment by orottier** [comment]
Alright, I have switched back internally to u32. The sample_rate function on the AudioContext still returns f32 but you can now use `sample_rate_raw` to get the high precision value

**Pull request merged**
