### PR TITLE
replace ULPS with absolute error

### PR DESCRIPTION
**Pull request by Jerboas86**
Remove all ULPS
- 0 ULPS -> 0. absolute error
- [sound] 40 ULPS -> 1.0e-10 absolute error (correspond to 200 db audio dynamic)
- [angle] 1 ULPS -> 0.001 absolute error (minimum audible angle is about 1-3 degrees) 

related to #53

### CODE REVIEW

**Comment by orottier** [comment]
Great progress. On my machine still fails
```
failures:
    node::iir_filter::test::default_periodic_wave_rendering_should_match_snapshot
    node::oscillator::tests::default_periodic_wave_rendering_should_match_snapshot
    node::oscillator::tests::default_sine_rendering_should_match_snapshot
    node::oscillator::tests::periodic_wave_rendering_should_match_snapshot
```

**Comment by Jerboas86** [comment]
Does it always fails, or succed sometimes ?

**Comment by orottier** [comment]
It always fails. Both on --debug and --release.
For the iir filter one, I need 1e-8 abs difference to succeed

**Comment by orottier** [comment]
No actually, it differs per run. So strange. What could be non-deterministic about this? 
Sometimes even 1e-8 is not enough margin for iir tests

**Comment by orottier** [comment]
I need the following margins to always succeed: (the iir filter algorithm may be numerically unstable?)
```
﻿﻿diff --git a/src/node/iir_filter.rs b/src/node/iir_filter.rs
index 0a39e2c..d4c5677 100644
--- a/src/node/iir_filter.rs
+++ b/src/node/iir_filter.rs
@@ -647,6 +647,6 @@ mod test {

         let min_len = min(data_ch.len(), ref_data_ch.len());

-        assert_float_eq!(data_ch[0..min_len], ref_data_ch[0..min_len], abs_all <= 0.);
+        assert_float_eq!(data_ch[0..min_len], ref_data_ch[0..min_len], abs_all <= 1.0);
     }
 }
diff --git a/src/node/oscillator.rs b/src/node/oscillator.rs
index 28dfc33..2385efe 100644
--- a/src/node/oscillator.rs
+++ b/src/node/oscillator.rs
@@ -1520,12 +1520,12 @@ mod tests {
         assert_float_eq!(
             output.channel_data(0).as_slice(),
             &ref_sine.data[..],
-            abs_all <= 1.0e-10
+            abs_all <= 1.0e-4
         );
         assert_float_eq!(
             output.channel_data(1).as_slice(),
             &ref_sine.data[..],
-            abs_all <= 1.0e-10
+            abs_all <= 1.0e-4
         );
     }

@@ -1637,12 +1637,12 @@ mod tests {
         assert_float_eq!(
             output.channel_data(0).as_slice(),
             &ref_sine.data[..],
-            abs_all <= 1.0e-10
+            abs_all <= 1.0e-6
         );
         assert_float_eq!(
             output.channel_data(1).as_slice(),
             &ref_sine.data[..],
-            abs_all <= 1.0e-10
+            abs_all <= 1.0e-6
         );
     }

@@ -1676,12 +1676,12 @@ mod tests {
         assert_float_eq!(
             output.channel_data(0).as_slice(),
             &ref_sine.data[..],
-            abs_all <= 1.0e-10
+            abs_all <= 1.0e-6
         );
         assert_float_eq!(
             output.channel_data(1).as_slice(),
             &ref_sine.data[..],
-            abs_all <= 1.0e-10
+            abs_all <= 1.0e-6
         );
     }
 }
 ```

**Comment by Jerboas86** [comment]
I found that [magic thing](https://isocpp.org/wiki/faq/newbie#floating-point-arith2)

**Comment by orottier** [comment]
Thanks for the link, interesting read!
I'm not sure what is the best way forward now. I can merge your work so far but the large numerical instability of the oscillator and iir may cause issues in real world application so definitely something to look into later.

**Comment by Jerboas86** [comment]
I agree that the instability is too big to be ignored. 

Unfortunately, i didn't succeed to reproduce the bug on my machine, so i don't think i am the best person to debug it.
Nevertheless, i could add lock-free write capability to `Snapshot` and make the debugging easier in general.

Note about IIR: instability detection is in the spec but not in the crate

**Comment by orottier** [comment]
I have fixed the merge conflict and increased the error margin so it always succeeds on my machine. No debugging done yet

**Pull request merged**
