### PR TITLE
AudioParam: Reduce code duplication and Arc usage

### PR DESCRIPTION
**Pull request by uklotzde**
- Extract common fields into `AudioParamBase`
- Extract atomic fields into `AudioParamShared`, wrapped into a single `Arc`

The code might not be elegant. But revealing and making those dependencies explicit is the first step before improving the design.

The static decomposition should not have any noticeable impact on performance or memory usage, although the compiler now has less options for reordering and packing the fields. Using only a single `Arc` instead of two could improve performance slightly.

### CODE REVIEW

**Comment by orottier** [comment]
Thanks again.

The explicit layout of `AudioParam > AudioParamRaw > AudioParamBase > AudioParamShared` has some merits but snippets like this are rather daunting:

```rust
        self.raw_parts
            .base_parts
            .shared_parts
            .current_value
            .store(clamped, Ordering::SeqCst);
```

> But revealing and making those dependencies explicit is the first step before improving the design.

Do you have any specific ideas or issues to address? It would help me decide whether this new layout pulls its weight

**Comment by uklotzde** [comment]
> Do you have any specific ideas or issues to address? It would help me decide whether this new layout pulls its weight

These chains only appear internally and the actual memory layout is not visible from the outside. Reducing the redundancies upfront might be helpful when sorting out the synchronization between `AudioParam` and `AudioParamProcessor` as proposed in #297. Sure, they are not elegant. But that's a consequence of the current design which does not seem to be ideal.

I prefer to group multiple fields that appear repeatedly in different contexts as distinct types. Replicating them anonymously across different types would hide these dependencies. Makes it easier to spot commonalities and differences for subsequent refactorings. We should end up with very few types that share only a single, common core or base.

**Comment by orottier** [comment]
Thanks for the elaborate reply.

> current design which does not seem to be ideal.
> subsequent refactorings

My question about specific ideas or issues to address still stands. I'm hesitant to refactor for the sake of abstract reasons such as redundancies and commonalities if there is no pressing issue at hand. Surely, you are technically correct about the flat layout hiding possible future improvements, but to refactor also incurs a slight cost since the original authors of the file will have to grok the changes.

It would really help me make a judgement if you could share the next steps you have in mind with this module.

**Comment by uklotzde** [comment]
The issues I tried to fix are probably only the tip of the iceberg.

**Pull request closed without merging**
